from src.database.config import supabase
from datetime import datetime, timedelta

import bcrypt


# Convert plain password into encrypted password before storing in database
def hash_pass(pwd):
    return bcrypt.hashpw(pwd.encode(), bcrypt.gensalt()).decode()


# Verify entered password with stored encrypted password
def check_pass(pwd, hashed):
    return bcrypt.checkpw(pwd.encode(), hashed.encode())


# Check whether username already exists
# Used during teacher registration
def check_teacher_exists(username):
    response = supabase.table("teachers").select("username").eq("username", username).execute()
    return len(response.data) > 0


# Create new teacher account
# Password is stored in encrypted format
def create_teacher(username, password, name):

    data = {
        "username": username,
        "password": hash_pass(password),
        "name": name
    }

    response = supabase.table("teachers").insert(data).execute()
    return response.data


# Teacher login using username and password
def teacher_login(username, password):

    response = supabase.table("teachers").select("*").eq("username", username).execute()

    if response.data:
        teacher = response.data[0]

        if check_pass(password, teacher['password']):
            return teacher

    return None


# Fetch all students from database
# Used for face recognition training and attendance
def get_all_students():
    response = supabase.table('students').select("*").execute()
    return response.data


# Create new student profile
# Stores face embedding and optional voice embedding
def create_student(new_name, face_embedding=None, voice_embedding=None):

    data = {
        'name': new_name,
        'face_embedding': face_embedding,
        'voice_embedding': voice_embedding
    }

    response = supabase.table('students').insert(data).execute()
    return response.data


# Teacher creates a new subject
def create_subject(subject_code, name, section, teacher_id):

    data = {
        "subject_code": subject_code,
        "name": name,
        "section": section,
        "teacher_id": teacher_id
    }

    response = supabase.table("subjects").insert(data).execute()
    return response.data


# Fetch all subjects created by a teacher
# Also calculate total students and total attendance sessions
def get_teacher_subjects(teacher_id):

    response = supabase.table('subjects').select(
        "*, subject_students(count), attendance_logs(timestamp)"
    ).eq("teacher_id", teacher_id).execute()

    subjects = response.data

    for sub in subjects:

        # Count total enrolled students
        sub['total_students'] = (
            sub.get("subject_students", [{}])[0].get('count', 0)
            if sub.get('subject_students')
            else 0
        )

        # Count unique attendance sessions
        attendance = sub.get('attendance_logs', [])

        unique_sessions = len(
            set(log['timestamp'] for log in attendance)
        )

        sub['total_classes'] = unique_sessions

        # Remove unwanted nested data
        sub.pop('subject_students', None)
        sub.pop('attendance_logs', None)

    return subjects


# Enroll student into a subject
# subject_students acts as junction table
def enroll_student_to_subject(student_id, subject_id):

    data = {
        'student_id': student_id,
        "subject_id": subject_id
    }

    response = supabase.table('subject_students').insert(data).execute()
    return response.data


# Remove student from a subject
def unenroll_student_to_subject(student_id, subject_id):

    response = supabase.table('subject_students').delete().eq(
        'student_id', student_id
    ).eq(
        'subject_id', subject_id
    ).execute()

    return response.data


# Fetch all subjects enrolled by a student
def get_student_subjects(student_id):

    response = supabase.table('subject_students').select(
        '*, subjects(*)'
    ).eq(
        'student_id', student_id
    ).execute()

    return response.data


# Fetch attendance history of a student
def get_student_attendance(student_id):

    response = supabase.table('attendance_logs').select(
        '*, subjects(*)'
    ).eq(
        'student_id', student_id
    ).execute()

    return response.data


# Store attendance records generated by AI attendance system
def create_attendance(logs):

    response = supabase.table('attendance_logs').insert(logs).execute()
    return response.data


# Fetch attendance records for subjects owned by a teacher
def get_attendance_for_teacher(teacher_id):

    response = supabase.table('attendance_logs').select(
        "*, subjects!inner(*)"
    ).eq(
        'subjects.teacher_id',
        teacher_id
    ).execute()

    return response.data


def create_attendance_session(subject_id, teacher_id, duration_minutes=10):

    start_time = datetime.now()
    end_time = start_time + timedelta(minutes=duration_minutes)

    result = (
        supabase.table("attendance_sessions")
        .insert({
            "subject_id": subject_id,
            "teacher_id": teacher_id,
            "start_time": start_time.isoformat(),
            "end_time": end_time.isoformat(),
            "is_active": True
        })
        .execute()
    )

    return result.data

def get_attendance_session_details(subject_id, timestamp):

    response = (
        supabase
        .table("attendance_logs")
        .select("*, students(*)")
        .eq("subject_id", subject_id)
        .eq("timestamp", timestamp)
        .execute()
    )

    return response.data


def get_active_session(subject_id):

    result = (
        supabase.table("attendance_sessions")
        .select("*")
        .eq("subject_id", subject_id)
        .eq("is_active", True)
        .execute()
    )

    return result.data



def get_student_attendance_percentage(student_id):

    logs = get_student_attendance(student_id)

    if not logs:
        return {}

    subject_stats = {}

    for log in logs:

        subject_name = log['subjects']['name']

        if subject_name not in subject_stats:

            subject_stats[subject_name] = {
                'present': 0,
                'total': 0
            }

        subject_stats[subject_name]['total'] += 1

        if log['is_present']:
            subject_stats[subject_name]['present'] += 1

    for subject in subject_stats:

        present = subject_stats[subject]['present']
        total = subject_stats[subject]['total']

        percentage = round(
            (present / total) * 100,
            2
        ) if total else 0

        subject_stats[subject]['percentage'] = percentage

    return subject_stats
# =====================================================
# DATABASE FLOW
# =====================================================
#
# 1. Teacher registers account.
# 2. Password is encrypted using bcrypt.
# 3. Teacher logs in using username and password.
# 4. Teacher creates subjects.
# 5. Student registers using Face ID and optional Voice ID.
# 6. Face and voice embeddings are stored in database.
# 7. Student enrolls into subjects.
# 8. AI recognizes student using face recognition.
# 9. Attendance records are stored in attendance_logs table.
# 10. Teacher views attendance reports.
# 11. Student views enrolled subjects and attendance history.
#
# =====================================================